### ISSUE TITLE
Allow key/values groupings using dot.

### ISSUE THREAD

**Issue by michaelhenry** [michaelhenry/Localizr#18]
Example:

```
pirate.time.formats.short = arrrround %H'ish
```

Will be 

Yml format:
```yml
pirate:
  time:
    formats:
      short: "arrrround %H'ish"
```

In json format
```json
{"pirate.time.formats.short":"arrrround %H'ish"}
```
And so on...
